In [ ]:
================== Data Analysis ====================
1. Pandas              : Data frame analysis
2. Numpy               : Numerical analysis
3. matplotlib          : Graphs and plots
4. seaborn             : plots
5. Bokhe               : plots
6. plotly              : plots

================== Machine Learning =================
7. stats               : for statistical models
8. scikit-learn(sklearn) : ML models

================== Deep Learning ====================

9. opencv         : Computer vision
10.pillow          : image operations
11. tensorflow     : neural network creations(developed by the google)
12. keras          : Neural Network
13. pytorch        : alternative package of tensorflow (facebook meta)


======================= NLP ===============================

14. NLTK       : natural language toolkit
15. spacy      : Alternative to NLTK
16.wordcloud   : most frequent occured word


============================== Scarapping =================================

17. Sqlite      :   Data base creation
18. Beautiful soup
19. Selenium

================================ API CREATION =============================
    
20 . Flask
21.  Fastapi
22 . Gradio
23.  DJango

================================== UPI CREATION =============================

24. streamlit



====================================== Transfer learning models (DL) ===========================

25.  Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. YOLO   : ultra analytics


======================================  Transfer Learning Models ==============================

30. Word2vec
31. GloVe


======================================= Huging Face Transformations ===================================

32. BERT  : Bi Directional Encoder  representation of Transformers



=======================================  Allen NLP  ============================================

33. Allen NLP packages


======================================  GENAI   ============================================

34. LangChain
35. Google Gemini related packages
36. OpenAI GPT related packages
37. Amazon Bedrock related packages
38. Meta , Llama  related packages


============================================================ Image and Video Generations ==================================

39. GAN models related packages
40. SORA related packages


==================================================  Cloud Applications =====================================

43. Azure ML related packages
44. GCP vertexAI related packages
45. AWS Sagemaker realted packages

==================== small ====================
46. time
47. logging
48. math
49. random
50. env
51. os

# step 1 = import packages

In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# step 2 = create a data frame using list

- data : you data either list or dictionary

- index = we need to provide in a list

- columns -  we need to provide in a list

In [102]:
names = ["ramesh","suresh","sathish"]
pd.DataFrame(names,index =["A" , "B","C"],columns=["Names"])

     Names
A   ramesh
B   suresh
C  sathish

In [103]:
names = ["ramesh","suresh","sathish"]
idx= [1,2,3]
age = [20,21,22]
pd.DataFrame(data = zip(names,age), index=idx , columns=["names","age"])

     names  age
1   ramesh   20
2   suresh   21
3  sathish   22

# step = 4

In [104]:
names = ["ramesh","suresh","sathish"]
age = [20,21,22]
pd.DataFrame(zip(names,age),columns=["names","age"])

     names  age
0   ramesh   20
1   suresh   21
2  sathish   22

# step - 5  create empty data frame and update the columns

In [105]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [106]:
df = pd.DataFrame()
df["names"] = ["ramesh" ,"suresh","sathish"]
df["age"] = [20,21,22]
df

     names  age
0   ramesh   20
1   suresh   21
2  sathish   22

In [107]:
df = pd.DataFrame(index=["A","B","C"])
df["names"] = ["ramesh" ,"suresh","sathish"]
df["age"] = [20,21,22]
df

     names  age
A   ramesh   20
B   suresh   21
C  sathish   22

# step - 6 : add a new column  with existing dataframe

In [137]:
names = ["ramesh","suresh","sathish"]
age = [20,21,22]
df = pd.DataFrame(zip(names,age),columns=["names","age"])
df["marks"] = [78,79,80]
df["city"] = ["hyderabad","banglore","mumbai"]
df

     names  age  marks       city
0   ramesh   20     78  hyderabad
1   suresh   21     79   banglore
2  sathish   22     80     mumbai

# step - 7: over write the columns values

- i want to overwrite my age values

- originally age is = [20,21,22]

- now i want to update the age = [30,31,32]

# name should be same other wise new column will create

In [138]:
df["age"]=[30,31,32]
df

     names  age  marks       city
0   ramesh   30     78  hyderabad
1   suresh   31     79   banglore
2  sathish   32     80     mumbai

-  here we wantedly created a unwanted column

In [143]:
df["Age"]=[30,31,32]
df

     names  age  marks       city  Age
0   ramesh   30     78  hyderabad   30
1   suresh   31     79   banglore   31
2  sathish   32     80     mumbai   32

# step -8 : drop the column

- labels

-  axis

-  index

- columns

- inplace

- now we drop the unwanted column

In [144]:
df

     names  age  marks       city  Age
0   ramesh   30     78  hyderabad   30
1   suresh   31     79   banglore   31
2  sathish   32     80     mumbai   32

In [141]:
df.drop("Age") # it is wrong approach

KeyError: "['Age'] not found in axis"

In [142]:
df.drop("Age" ,axis=0) # Wrong approach

KeyError: "['Age'] not found in axis"

In [145]:
df.drop("Age",axis=1)
df

     names  age  marks       city  Age
0   ramesh   30     78  hyderabad   30
1   suresh   31     79   banglore   31
2  sathish   32     80     mumbai   32

In [146]:
 # we are not able to see the changes in the data
# because we didnot apply inplace is True

In [147]:
df

     names  age  marks       city  Age
0   ramesh   30     78  hyderabad   30
1   suresh   31     79   banglore   31
2  sathish   32     80     mumbai   32

In [150]:
# when ever we use columns label
# no need of axis
df.drop(columns=["Age"],inplace = True)
df

     names  age  marks       city
0   ramesh   30     78  hyderabad
1   suresh   31     79   banglore
2  sathish   32     80     mumbai

In [151]:
# drop index 2
df.drop(index = 2,inplace = True)

In [152]:
df

    names  age  marks       city
0  ramesh   30     78  hyderabad
1  suresh   31     79   banglore

# step  - 9 

- remane the column

In [153]:
df

    names  age  marks       city
0  ramesh   30     78  hyderabad
1  suresh   31     79   banglore

In [157]:
dict1 = {"city" : "Cities"}
df.rename(dict1)  # herre it will show

    names  age  marks       city
0  ramesh   30     78  hyderabad
1  suresh   31     79   banglore

In [160]:
df.rename(columns=dict1,inplace = True)
df

    names  age  marks     Cities
0  ramesh   30     78  hyderabad
1  suresh   31     79   banglore

In [161]:
df.rename(dict1,axis =1,inplace = True)
df

    names  age  marks     Cities
0  ramesh   30     78  hyderabad
1  suresh   31     79   banglore

In [163]:
dict1 = {1:"B"}
df.rename(index = dict1 , inplace = True)
df

    names  age  marks     Cities
0  ramesh   30     78  hyderabad
B  suresh   31     79   banglore

In [170]:
df1 = pd.DataFrame()
df1["value"] = [i for i in range (1,11)]
df1["square_value"] = [i**2 for i in range(1,11)]
df1["cibe_value"] = [i**3 for i in range(1,11)]

In [171]:
df1

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [ ]:
- len

- columns

- shape

- dtypes

- head

- tail

In [172]:
df1.columns

Index(['value', 'square_value', 'cibe_value'], dtype='object')

In [179]:
list(df1.columns)

['value', 'square_value', 'cibe_value']

In [181]:
df1.columns.to_list()

['value', 'square_value', 'cibe_value']

In [175]:
df1.shape

(10, 3)

In [176]:
df1.dtypes

# for integer it will come int

value           int64
square_value    int64
cibe_value      int64
dtype: object

In [182]:
df1.head()

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125

In [183]:
df1.tail()

   value  square_value  cibe_value
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [184]:
len(df1)

10

In [186]:
df1.isnull()

# we are asking the question
#a null value available or not
# True or False
# True means null value available
# false means null value not available

   value  square_value  cibe_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False
9  False         False       False

In [187]:
df1.isnull().sum()
# column  wise nall value count

value           0
square_value    0
cibe_value      0
dtype: int64

In [188]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         10 non-null     int64
 1   square_value  10 non-null     int64
 2   cibe_value    10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

# step number = 10

# how to change a specific value of a column

# df1.drop

# either it will drop column

In [208]:
df1.replace({"cibe_value":{1 : 23}})

   value  square_value  cibe_value
0      1             1          23
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [ ]:

>>> df.replace({'A': {0: 100, 4: 400}})
        A  B  C
0  100  5  a
1    1  6  b
2    2  7  c
3    3  8  d
4  400  9  e

In [205]:
df1.replace(64,464)

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729
9     10           100        1000

In [ ]:
df

# step-11 selection of columns

In [195]:
df1["cibe_value"]

0       1
1       8
2      27
3      64
4     125
5     216
6     343
7     512
8     729
9    1000
Name: cibe_value, dtype: int64

In [196]:
type(df1)

pandas.core.frame.DataFrame

In [197]:
type(df1["cibe_value"])

pandas.core.series.Series

# series look like data frame
# rows and columes

In [199]:
df1["cibe_value"].shape

(10,)

# beacause series it is a 1 dimentional

In [200]:
df1.shape

(10, 3)

# because data is a 2 dimentional

In [201]:
df1["cibe_value"]

0       1
1       8
2      27
3      64
4     125
5     216
6     343
7     512
8     729
9    1000
Name: cibe_value, dtype: int64

In [202]:
df1[["cibe_value"]]

   cibe_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729
9        1000

In [204]:
type(df1[["cibe_value"]])

pandas.core.frame.DataFrame

In [210]:
# square_value

# cube_value

# multiplr always keep thoses in lisst

df1[["cibe_value","square_value"]]

   cibe_value  square_value
0           1             1
1           8             4
2          27             9
3          64            16
4         125            25
5         216            36
6         343            49
7         512            64
8         729            81
9        1000           100

In [211]:
df1

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [213]:
df1

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16       46444
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

# step - 12 : how to append a row

# - loc

- df1.loc(rows,columns)

- df1,iloc(rows,columns)


- we need to select a particular rows and columns using list[start:stop:step]

In [216]:
df1.loc[3:7]

   value  square_value  cibe_value
3      4            16       46444
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512

In [220]:
df1.iloc[3:7,1:3]

   square_value  cibe_value
3            16       46444
4            25         125
5            36         216
6            49         343

In [221]:
df1.loc[3:7,["square_value","cibe_value"]]

   square_value  cibe_value
3            16       46444
4            25         125
5            36         216
6            49         343
7            64         512

In [222]:
cols= ["square_value","cibe_value"]
df1.loc[1:9,cols]

   square_value  cibe_value
1             4           8
2             9          27
3            16       46444
4            25         125
5            36         216
6            49         343
7            64         512
8            81         729
9           100        1000

In [223]:
df1.iloc[[1,2,3]]

   value  square_value  cibe_value
1      2             4           8
2      3             9          27
3      4            16       46444

In [240]:
df1.iloc[[2]] # it is in [] so it is a dataframe

   value  square_value  cibe_value
2      3             9          27

In [228]:
df1.iloc[2]  # converted to series

value            3
square_value     9
cibe_value      27
Name: 2, dtype: int64

In [229]:
df1.iloc[[2,3,4],[0,2]]

   value  cibe_value
2      3          27
3      4       46444
4      5         125

In [230]:
df1.iloc[2,0]

np.int64(3)

In [234]:
df1.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: value, dtype: int64

In [241]:
df1.iloc[2,:]

value            3
square_value     9
cibe_value      27
Name: 2, dtype: int64

In [236]:
df1.iloc[[2],:]

   value  square_value  cibe_value
2      3             9          27

In [237]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [238]:
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

# how to append a row

In [242]:
df1

   value  square_value  cibe_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16       46444
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [246]:
df1.loc[10] = [12, 300 , 4000]

In [247]:
df1

    value  square_value  cibe_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16       46444
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      11           200        3000
10     12           300        4000

In [250]:
ID = len(df1)
ID

11

In [258]:
df1.loc[ID] = [13,400,5000]

In [259]:
df1

    value  square_value  cibe_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16       46444
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      11           200        3000
10     12           300        4000
11     13           400        5000

# how to save the dataframes

- we can save dataframes in two ways

- .csv

- .xlsx

- where i want to to save : directory

- what is the filename to save : file name

- what is the  type of file : extension

- different folder = "C:\Users\Admin\Documents\naresh IT\EDA practice\data1.csv"

- different folder = "C:\Users\Admin\Documents\naresh IT\EDA practice\data1.csv"

- same folder = "data1.csv" or "data.xlsx"

In [253]:
csv_path = r"C:\Users\Admin\Documents\naresh IT\EDA practice\data1.csv"
excel_path = r"C:\Users\Admin\Documents\naresh IT\EDA practice\data1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

In [263]:
csv_path = r"data1.csv"
excel_path = r"data1.xlsx"
df1.to_csv(csv_path,index=False)
df1.to_excel(excel_path)

# step - 14 read the data

In [261]:
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cibe_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16       46444
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     11           200        3000
10          10     12           300        4000

In [262]:
pd.read_excel(excel_path)

    Unnamed: 0  value  square_value  cibe_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16       46444
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     11           200        3000
10          10     12           300        4000

In [264]:
# changed index = False

In [265]:
pd.read_csv(csv_path)

    value  square_value  cibe_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16       46444
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      11           200        3000
10     12           300        4000
11     13           400        5000

In [ ]:
csv_path = r"data1.csv"
excel_path = r"data1.xlsx"
df1.to_csv(csv_path,index=False)
df1.to_excel(excel_path)