- generally ML models Developed by maths

- convert catogorical data to the numerical columns

- here we are transforming the data

- the method is called as encoding

- feature Analysis = first 9 sessions

- feature Engineering = transform the data

- feature selection = meachine learning

- before Model Development

- we will do EDA  : Exploratory data analysis

- features(columns) analysis

- Catogorical , numerical , outlier analysis , bivariance , multivariance

- we will get the insights


- ** feature Engineering **

- we will modify the data

- models develop by maths

- Encoding : convert catagorical data to numerical Variables

- scaling : all the numerical columns makes under scale

- transformations : all the maths developed by assumption data follows normal distribution

- convert skewed distribution to Normal

- ** feature selection **

In [ ]:
# map

#

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visadata_df = pd.read_csv("Visadataset.csv")

In [3]:
cat = visadata_df.select_dtypes(include="object").columns
num = visadata_df.select_dtypes(exclude="object").columns

In [4]:
visadata_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

# create a dictionary for each labels based on alphabetical order

In [7]:
d = {"Certified ": 0 , "Denied" : 1}
d

{'Certified ': 0, 'Denied': 1}

In [8]:
# map the dictionary with column
visadata_df['case_status'].map(d)

0        1.0
1        NaN
2        1.0
3        1.0
4        NaN
        ...
25475    NaN
25476    NaN
25477    NaN
25478    NaN
25479    NaN
Name: case_status, Length: 25480, dtype: float64

In [ ]:
we will over write in same

In [26]:
visadata_df = pd.read_csv("Visadataset.csv")
visadata_df['case_status'].unique()
d = {"Certified" : 0 , "Denied" : 1}
visadata_df['case_status'] = visadata_df['case_status'].map(d)

In [27]:
visadata_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [28]:
# visadata_df = pd.read_csv("Visadataset.csv")
unique = sorted(visadata_df['continent'].unique())
d = {}
for i in range(len(unique)):
    d[unique[i]] = i
visadata_df['continent'] = visadata_df['continent'].map(d)

# dict comprehension

# d = {unique[i] : i for i in range(len(unique))}

In [29]:
visadata_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [39]:
"welcome".replace("z","Z")
#"welcome".find("z")
#"welcome".index("z")
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [40]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [42]:
visadata_df = pd.read_csv("Visadataset.csv")
for i in cat[1:]:
    #visadata_df = pd.read_csv("Visadataset.csv")
    unique = sorted(visadata_df[i].unique())
    d = {unique[i] : i for i in range(len(unique))}
    visadata_df[i] = visadata_df[i].map(d)
    
    #d = {}
    #for i in range(len(unique)):
     #   d[unique[i]] = i
    #visadata_df[i] = visadata_df[i].map(d)
    
    # dict comprehension
    
    # d = {unique[i] : i for i in range(len(unique))}

# label encoder

- package name = "sklearn"
        - class = "preprocessing"
                - method = "LabelEncoder"

- from  sklearn.preprocessing import LabelEncoder

In [ ]:
step = 1 : import the method

step 2: save the method

step -2 : applt fit transform


** fit transform **

- fit : finding something

    - first we are finding dictionary

- fit-transform : changing the data

    - using the dictionary we are changing the english to numbers

In [44]:
from sklearn.preprocessing import LabelEncoder
visadata_df = pd.read_csv("Visadataset.csv")

le = LabelEncoder()
le.fit_transform(visadata_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [48]:
from sklearn.preprocessing import LabelEncoder
visadata_df = pd.read_csv("Visadataset.csv")

le = LabelEncoder()

for i in cat :
    visadata_df[i] = le.fit_transform(visadata_df[i])

In [49]:
visadata_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

** OneHotEncoder **

- the method name is : pd.get_dummies

|case_status|case_Denied|case_Certified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|

In [55]:
visadata_df = pd.read_csv("Visadataset.csv")

pd.get_dummies(visadata_df['continent'],
                    dtype="int")

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [53]:
visadata_df['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

# LabelEncoder vs OneHotEncoder

- Generally we dont want a relation between input columns

- we need both aput columns are not correlated each other

- we need both input columns are **independent(X,Y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve above

- But OneHotEncoder creates new columns

- columns are incraese means dimensions are incresae


- More dimension data need more processing time

- More dimension data need more infra

- this is called **CURSE OF DIMENSIONALITY**