In [7]:
import numpy as np
import pandas as pd
data = {"names" : ["ramesh" , "suresh" , "sathish" , np.nan] , 
       "age" : [np.nan , 22,25,27] ,
       "city" : ["pune" , "pune" , np.nan , "hyd"]}
df = pd.DataFrame(data= data)
df.to_csv("missing_values_numpy.csv" , index= False )
df

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0   NaN
3      NaN  27.0   hyd

In [8]:
import numpy as np
import pandas as pd
data = {"names" : ["ramesh" , "suresh" , "sathish" , None] , 
       "age" : [None , 22,25,27] ,
       "city" : ["pune" , "pune" , None , "hyd"]}
df1 = pd.DataFrame(data= data)
df1.to_csv("missing_values_None.csv" , index= False )
df1

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0  None
3     None  27.0   hyd

In [9]:
df.dtypes

names     object
age      float64
city      object
dtype: object

In [10]:
df1.dtypes

names     object
age      float64
city      object
dtype: object

In [12]:
df.isnull()

   names    age   city
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [13]:
df.isnull().sum()

names    1
age      1
city     1
dtype: int64

# fillna

In [14]:
df.fillna(30)

     names   age  city
0   ramesh  30.0  pune
1   suresh  22.0  pune
2  sathish  25.0    30
3       30  27.0   hyd

In [16]:
df['age'].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: age, dtype: float64

- --------------------------------------------------------------------------
- the above ine us we aew filling randomly
- all the columns are filled with random number
- it is not a good approach because in a data we have different data types

# what is the difference between np.nan and None

### in catagorical we will use **NONE**

### in numerical we will use **np.nan**

In [17]:
np.nan+5

nan

In [18]:
None + 5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [19]:
arr1 = np.array([1,2,np.nan,3])
arr2 = np.array([1,2,None , 3])

In [20]:
arr1

array([ 1.,  2., nan,  3.])

In [21]:
arr2

array([1, 2, None, 3], dtype=object)

In [22]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [24]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

 - np.nan represents **float type**

 - None represents **object type**

 - is data operations related to Maths then nan format is better

# fill the value based on a specific column

In [25]:
df["names"].fillna("manish")

0     ramesh
1     suresh
2    sathish
3     manish
Name: names, dtype: object

# Fill with methods

- when ever we are using methods no need to provide values

### methods are

- pad

- bfill

- ffill

- backfill

In [36]:
df

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0   NaN
3      NaN  27.0   hyd

In [40]:
import warnings
warnings.filterwarnings("ignore")
df.fillna(method = "pad" )

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0  pune
3  sathish  27.0   hyd

In [37]:
df

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0   NaN
3      NaN  27.0   hyd

In [33]:
df.fillna(method="bfill")

     names   age  city
0   ramesh  22.0  pune
1   suresh  22.0  pune
2  sathish  25.0   hyd
3      NaN  27.0   hyd

In [38]:
df

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0   NaN
3      NaN  27.0   hyd

In [34]:
df.fillna(method="ffill")

     names   age  city
0   ramesh   NaN  pune
1   suresh  22.0  pune
2  sathish  25.0  pune
3  sathish  27.0   hyd

In [35]:
df.fillna(method="backfill")

     names   age  city
0   ramesh  22.0  pune
1   suresh  22.0  pune
2  sathish  25.0   hyd
3      NaN  27.0   hyd

## MEAN_MEDIAN _MODE

- instead of filling with random values

- we can use mean median mode also

- for numerical columns use mean and meadian

- if Data outliers are there use **Median**

- for catagorical columns **mode**

In [45]:
age_mean = np.mean(df['age'])
df['age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: age, dtype: float64

In [50]:
age_mean

np.float64(24.666666666666668)

In [58]:
df['city'].mode().values.tolist()[0]

'pune'